TFIDF = [Term Frequency-Inverse Document Frequency](https://en.wikipedia.org/wiki/Tf%E2%80%93idf)

In [45]:
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import os
from string import punctuation
from datetime import datetime

DIRNAME = 'blogs/'

english_stopwords = set(stopwords.words('english') + list(punctuation) +
                       ['..','...','....','``',"''",'/n'])

In [46]:
def clean_wordlist(filelist):
    '''
    Takes a list of filenames with XML content, opens these, and provides a wordlist 
    for all these posts, lemmatized without stopwords.
    '''
    corpus = ''
    lemmatizer = WordNetLemmatizer()
    for eachfile in filelist:
        xmltext = open(eachfile, encoding = 'utf8', errors = 'replace').read()
        soup = BeautifulSoup(xmltext, features = 'xml')
        corpus += '/n'.join([x.text.lower() for x in soup.findAll('post')])
    wordlist = [lemmatizer.lemmatize(word) for word in word_tokenize(corpus)
               if word not in english_stopwords]
    return wordlist

In [47]:
blogfiles = [ DIRNAME + fn for fn in os.listdir(DIRNAME) if not fn.startswith('.')]

In [48]:
print(datetime.now().strftime('%H:%M:%S'))
allblogs = [' '.join(clean_wordlist([x])) for x in blogfiles[:1000] ]
print(datetime.now().strftime('%H:%M:%S'))

11:08:15
11:08:37

In [51]:
allblogs[575]

"introverted 62.5 extroverted e 37.5 imaginative n 64.71 realistic 35.29 emotional f 63.64 intellectual 36.36 easygoing p 73.33 organized j 26.67 type infp idealist possible profession include information-graphics designer college professor researcher legal mediator social worker holistic health practitioner occupational therapist diversity manager human resource development specialist employment development specialist minister/priest/rabbi missionary psychologist writer urllink get ca n't wish used 's way time n't take seriously 've fallen house fallen 's one else around stand two foot fight stay incomplete thought heard sound water drop fell ground turned around pick pace tear mixed rain ran face gathered left strength held arm length set ran away come back fight day write remember hate month december must paste look face act way n't feel world decide 's better hide one know real 's hard see would took mask began heal try relax let go die 's thing know sometimes stop ca n't take anymore human being bore learning bravest soul fall ’ found life time ’ time go lying nest naught ordered assembled paid without thought night place ’ gentle arm around wrap keep night fight sad war without carry despite comfort alone comfort seek tellingly outside mind 's label speak forced choice eroded conscience rare much better tomorrow closed eye would fare 12:23am – 01/12/04 c melissa 1. color kitchen plate usually white paper paper white n't away dirty 2. book reading heartbreaking work staggering genius dave egger 3. favorite board game trivial pursuit 4. 's mouse pad n't mousepad use tablet 5. favorite magazine q magazine best music publication ever also read occasional nme like print magazine relevant well 6. least favorite smell rotting corpse 7. first thing think wake morning sure would nice sleeping 8. favorite color surfer blue cmyk 50,30,15,0 9. least favorite color color application 10. many ring take answer phone depends middle calling 11. future child 's name girl kate katie maybe sure boy aidan hayden 12. important life real relationship love win know 13. chocolate vanilla chocolate chocolate covered chocolate tiny bit chocolate side 14. like drive fast cop cause passing old lady driving unsafe wanted get past slow back normal 5 really 's true 15. sleep stuffed animal n't sleep love stuffed animal 16. storm cool scary bigger better right 17. type first car 1990 white astro van fusia teal heart beat decal side 18. could meet one person dead alive france farmer 19. favorite drink water day alaskan amber night 20. birthday 25 july 21. eat stem broccoli wait brocolli edible 22. could job would studio engineer 23. hair color blonde 24. ever love yes 25. one favorite movie impossible go royal tennenbaums 26. type finger right key yes n't ms. wright would smack hand ruler swollen bruised 27. 's bed bed floor carpet cement dirt china think 29. favorite sport watch ncaa basketball 30. single biggest fear never finding soulmate 31. say one nice thing person sent melissa take great history note 33. favorite cd impossible listening alot delay sound like james suede bit think like sound like beach boy bit happy shiny 34. favorite tv show thing history channel discovery channel 35. ketchup mustard ketchup everything 36. hamburger hot-dogs vegetarian hamburger bonnie 's place hot dog yesterdog yeah guess still hungry would eat vegetarian 39. best place ever gull lake winter time everyone else gone 40. screen saver called flurry one mac o x screen saver spinning color wisp 41. burger king mcdonalds burger king though still plan launch franchise called mcburger queen day 42. favorite holiday 4th july 43. favorite day week sunday 's real day left n't 44. favorite season fall 45. know book bible though could recite order mean 46. could high school would think lucky enough thing played first time around 47. local bakery dunkin donut krispy kreme local bakery like dutch old world style donut 48. latest hobby building tiny getaway wood camp 49. would go next vacation going northern california saturday would love go europe somtime next couple year 50. like child n't yet hmmm guess 's"

In [56]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
tfidf_vectors = tfidf_vectorizer.fit_transform(allblogs)
# Creates a very large array. Documents at the top and then terms below.

In [57]:
as_array = tfidf_vectors.toarray()

In [61]:
feature_names = tfidf_vectorizer.get_feature_names_out()
# new version of sklearn requires additional "_out"

In [63]:
df = pd.DataFrame(as_array,columns=feature_names).T

In [64]:
df

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
00,0.0,0.057854,0.0,0.0,0.002331,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.006462,0.0,0.0,0.006001
000,0.0,0.000000,0.0,0.0,0.007195,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.040186,0.0,0.000000,0.0,0.0,0.003087
0000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
000000000001,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
黄河大合唱第一乐章,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
黄河船夫曲,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
ａｖｏｉｄ,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
ｇｏｏｄ,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
ｓｏ,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000

In [68]:
df[10000:100010]

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
bahrua,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
bahstun,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
baht,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
bahumbug,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
bahumut,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
weeel,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
weehee,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
weehooo,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
week,0.0,0.004671,0.0,0.0,0.058725,0.008726,0.005694,0.0,0.007398,0.0,...,0.045014,0.0,0.01019,0.06085,0.020501,0.0,0.064432,0.016502,0.0,0.015747
weekday,0.0,0.007925,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.012552,0.0,...,0.000000,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000